// <auto-generated />
namespace bizcard.online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedrequiredfieldvalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrequiredfieldvalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201602160247019_added required field validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
