// <auto-generated />
namespace bizcard.online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removedminrequirementformessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedminrequirementformessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201602160356217_Removed min requirement for message."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
